name: mock_data
description: Generate random data(string, integer, IPs and more).
version: 1.2.1
homepage: https://github.com/PinkFrojd/mock_data
author: Dinko Pehar <dinko.pehar.dev@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
